language: node_js
node_js:
- '7.3.0'
addons:
  code_climate:
    repo_token: 1d74e14d8b4235f5b311de8a5b9e567b178e10dc2226130034184fba0f93a759
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install: 
  - npm install
  - npm install codeclimate-test-reporter
script:
  - karma start
after_script:
  - "cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js"
  - codeclimate-test-reporter < coverage/lcov.info